import type { FailurePattern } from './types';

export const FAILURE_PATTERNS: readonly FailurePattern[] = [
  {
    id: 'oom',
    name: 'Out of Memory',
    category: 'infra',
    severity: 'critical',
    patterns: [
      /Cannot allocate memory/i,
      /exit code 137/i,
      /Java heap space/i,
      /OOMKilled/i,
      /OutOfMemoryError/i,
      /ENOMEM/i,
    ],
    description:
      'The build ran out of memory. This is typically an infrastructure issue — the agent does not have enough RAM for this workload.',
    remediationSteps: [
      'Check if your build has a memory leak (e.g., unbounded caching in tests).',
      'Increase memory allocation in your Jenkinsfile (e.g., -Xmx for Java builds).',
      'If this is a container build, increase the container memory limit.',
      'If the issue persists across multiple jobs, contact DevOps — the agent may need more RAM.',
    ],
  },
  {
    id: 'timeout',
    name: 'Build Timeout',
    category: 'infra',
    severity: 'high',
    patterns: [
      /Timeout has been exceeded/i,
      /deadline exceeded/i,
      /timed out/i,
      /Build timed out/i,
      /Cancelling nested steps due to timeout/i,
    ],
    description:
      'The build exceeded its time limit. This may be caused by a slow test, an infinite loop, or waiting on an unavailable resource.',
    remediationSteps: [
      'Check if a test is hanging or running much longer than usual.',
      'Look for infinite loops or unbounded retries in recently changed code.',
      'Verify that all external dependencies (databases, APIs) are reachable from the build agent.',
      'If the build is legitimately slow, consider increasing the timeout in your Jenkinsfile.',
    ],
  },
  {
    id: 'test-failure',
    name: 'Test Failure',
    category: 'code',
    severity: 'medium',
    patterns: [
      /Tests run:.*Failures:\s*[1-9]/i,
      /FAILED\s+\[/,
      /AssertionError/i,
      /AssertError/i,
      /expected\s+.*\s+but\s+got/i,
      /test.*failed/i,
      /FAIL\s+src\//,
      /✕|✖|FAIL/,
    ],
    description:
      'One or more tests failed. This is a code issue — check the failing test for details.',
    remediationSteps: [
      'Look at the test name and assertion message in the log below.',
      'Run the failing test locally to reproduce.',
      'Check if this test is known to be flaky (has it passed recently on the same branch?).',
      'Fix the test or the code it validates, then push again.',
    ],
  },
  {
    id: 'compilation',
    name: 'Compilation Error',
    category: 'code',
    severity: 'high',
    patterns: [
      /error:\s*cannot find symbol/i,
      /BUILD FAILED/i,
      /error TS\d+/i,
      /SyntaxError/i,
      /Compilation failed/i,
      /error\[E\d+\]/,
      /cannot find module/i,
    ],
    description:
      'The code failed to compile. This is a code issue — there is a syntax or type error in the source.',
    remediationSteps: [
      'Read the error message carefully — it tells you the file, line, and what went wrong.',
      'Run the build locally (e.g., `tsc --noEmit` for TypeScript, `mvn compile` for Java).',
      'Check if a recent rename or deletion broke an import.',
      'Fix the compilation error and push again.',
    ],
  },
  {
    id: 'dependency',
    name: 'Dependency Resolution Failed',
    category: 'code',
    severity: 'high',
    patterns: [
      /Could not resolve dependencies/i,
      /404 Not Found.*\.(jar|tgz|whl)/i,
      /npm ERR! 404/i,
      /ModuleNotFoundError/i,
      /Could not find artifact/i,
      /ERESOLVE/i,
      /peer dep/i,
    ],
    description:
      'A dependency could not be resolved. This is usually a code issue — a package was removed, renamed, or has a version conflict.',
    remediationSteps: [
      'Check if the failing package name and version exist in the registry.',
      'Run `npm install` (or equivalent) locally to reproduce the error.',
      'Check for conflicting peer dependency versions.',
      'If a private registry is down, this may be an infra issue — check with DevOps.',
    ],
  },
  {
    id: 'disk-full',
    name: 'Disk Space Exhausted',
    category: 'infra',
    severity: 'critical',
    patterns: [
      /No space left on device/i,
      /ENOSPC/i,
      /disk usage.*100%/i,
      /insufficient disk space/i,
    ],
    description:
      'The build agent ran out of disk space. This is an infrastructure issue — not your fault.',
    remediationSteps: [
      'This is an infrastructure issue. Your code is not at fault.',
      'The build agent needs disk cleanup or a larger disk.',
      'Contact DevOps to address the disk space issue.',
      'Your build will succeed once the agent has enough space — try re-running.',
    ],
  },
  {
    id: 'agent-disconnected',
    name: 'Agent Disconnected',
    category: 'infra',
    severity: 'critical',
    patterns: [
      /Agent\s+.*\s+is offline/i,
      /Connection was broken/i,
      /java\.nio\.channels\.ClosedChannelException/i,
      /Slave went offline/i,
      /hudson\.remoting/i,
    ],
    description:
      'The build agent disconnected during the build. This is an infrastructure issue — not your fault.',
    remediationSteps: [
      'This is an infrastructure issue. Your code is not at fault.',
      'The agent lost connection — this could be a network issue or the agent crashed.',
      'Re-run the build. If it keeps happening, contact DevOps.',
      'Check the Health page to see if other agents are affected.',
    ],
  },
  {
    id: 'network',
    name: 'Network Failure',
    category: 'infra',
    severity: 'high',
    patterns: [
      /UnknownHostException/i,
      /Connection refused/i,
      /ETIMEDOUT/i,
      /SSL handshake/i,
      /ECONNRESET/i,
      /ENOTFOUND/i,
      /getaddrinfo/i,
    ],
    description:
      'A network connection failed during the build. This may be a temporary infrastructure issue.',
    remediationSteps: [
      'Check if the failing host is a dependency your build needs (registry, database, API).',
      'Re-run the build — transient network issues often resolve themselves.',
      'If the issue persists, check the Health page for infrastructure problems.',
      'Contact DevOps if a specific internal service is unreachable.',
    ],
  },
  {
    id: 'permission',
    name: 'Permission Denied',
    category: 'infra',
    severity: 'high',
    patterns: [
      /Permission denied/i,
      /403 Forbidden/i,
      /Access Denied/i,
      /authentication required/i,
      /not authorized/i,
    ],
    description:
      'The build was denied access to a resource. This may be a credentials or permissions issue.',
    remediationSteps: [
      'Check if the build requires credentials that may have expired.',
      'Verify that your Jenkinsfile references the correct credentials ID.',
      'If accessing a private registry or API, check that the service account has permissions.',
      'Contact DevOps if you believe your permissions should be granted.',
    ],
  },
  {
    id: 'docker',
    name: 'Docker / Container Issue',
    category: 'infra',
    severity: 'high',
    patterns: [
      /Cannot connect to the Docker daemon/i,
      /image.*not found/i,
      /Error response from daemon/i,
      /docker:.*not found/i,
      /pull access denied/i,
    ],
    description:
      'A Docker-related error occurred. This may be an infrastructure issue (daemon down) or a code issue (wrong image name).',
    remediationSteps: [
      'If "Cannot connect to Docker daemon" — this is an infra issue. Contact DevOps.',
      'If "image not found" — check the image name and tag in your Dockerfile or Jenkinsfile.',
      'If "pull access denied" — ensure the build has credentials to pull from the registry.',
      'Try re-running the build. Docker daemon issues are often transient.',
    ],
  },
  {
    id: 'scm',
    name: 'SCM Checkout Failed',
    category: 'infra',
    severity: 'high',
    patterns: [
      /Failed to checkout/i,
      /fatal: repository.*not found/i,
      /Authentication failed for/i,
      /Could not read from remote repository/i,
      /Git checkout failed/i,
    ],
    description:
      'Jenkins failed to check out the source code. This may be a credential or repository access issue.',
    remediationSteps: [
      'Verify the repository URL is correct in the job configuration.',
      'Check if the Git credentials configured in Jenkins have expired.',
      'If the repo was recently renamed or moved, update the job configuration.',
      'Contact DevOps if this error started happening across multiple jobs.',
    ],
  },
  {
    id: 'lint',
    name: 'Lint / Style Violation',
    category: 'code',
    severity: 'low',
    patterns: [
      /eslint.*error/i,
      /checkstyle/i,
      /found\s+\d+\s+error/i,
      /flake8/i,
      /pylint/i,
      /prettier.*--check/i,
    ],
    description:
      'Code style or linting checks failed. This is a code issue — fix the violations and push again.',
    remediationSteps: [
      'Run the linter locally: check your package.json or Makefile for the lint command.',
      'Many lint errors can be auto-fixed (e.g., `npm run lint -- --fix`).',
      'Fix remaining errors manually based on the error messages.',
      'Push the fixes and the build should pass.',
    ],
  },
] as const;
